name: Security Scan

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ####################################
      # Secret Scanning
      ####################################

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ####################################
      # IaC Security
      ####################################

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Checkov Terraform Scan
        run: |
          checkov \
            -d . \
            --framework terraform \
            --output cli

      ####################################
      # Vulnerability Scanner
      ####################################

      - name: Trivy Config Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1